apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.jenkins.storage.pv.name }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.jenkins.storage.size }}
  accessModes:
    - {{ .Values.jenkins.storage.accessMode }}
  hostPath:
    path: {{ .Values.jenkins.storage.pv.hostPath }}
